In [2]:
#librerias
import json
import pandas as pd
import os

In [3]:
#Cargar el archivo en un file_path para tenerlo en una variable

file_path = '/Users/luisalbertocerelli/Desktop/00-Todo/Data_Science/01-Full_Time/TPFINAL/Yelp/notebooks_yelp/user_parquet_yelp/user.parquet'

In [4]:
#leer el archivo parquet desde el file_path

df_user = pd.read_parquet(file_path)

In [4]:
#analizamos el peso del archivo original
import os
print("Tamaño del archivo original: ", os.path.getsize(file_path)/1e6, "MB")

Tamaño del archivo original:  2950.715751 MB

In [5]:
df_user.shape

(2105597, 22)

In [6]:
df_user

,user_id,name,review_count,yelping_since,useful,funny,cool,elite,friends,fans,...,compliment_more,compliment_profile,compliment_cute,compliment_list,compliment_note,compliment_plain,compliment_cool,compliment_funny,compliment_writer,compliment_photos
0,qVc8ODYU5SZjKXVBgXdI7w,Walker,585,2007-01-25 16:47:26,7217,1259,5994,2007,"NSCy54eWehBJyZdG2iE84w, pe42u7DcCH2QmI81NX-8qA...",267,...,65,55,56,18,232,844,467,467,239,180
1,j14WgRoU_-2ZE1aw1dXrJg,Daniel,4333,2009-01-25 04:35:42,43091,13066,27281,"2009,2010,2011,2012,2013,2014,2015,2016,2017,2...","ueRPE0CX75ePGMqOFVj6IQ, 52oH4DrRvzzl8wh5UXyU0A...",3138,...,264,184,157,251,1847,7054,3131,3131,1521,1946
2,2WnXYQFK0hXEoTxPtV2zvg,Steph,665,2008-07-25 10:41:00,2086,1010,1003,"2009,2010,2011,2012,2013","LuO3Bn4f3rlhyHIaNfTlnA, j9B4XdHUhDfTKVecyWQgyA...",52,...,13,10,17,3,66,96,119,119,35,18
3,SZDeASXq7o05mMNLshsdIA,Gwen,224,2005-11-29 04:38:33,512,330,299,"2009,2010,2011","enx1vVPnfdNUdPho6PH_wg, 4wOcvMLtU6a9Lslggq74Vg...",28,...,4,1,6,2,12,16,26,26,10,9
4,hA5lMy-EnncsH4JoR-hFGQ,Karen,79,2007-01-05 19:40:59,29,15,7,,"PBK4q9KEEBHhFvSXCUirIw, 3FWPpM7KU1gXeOM_ZbYMbA...",1,...,1,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2105592,4QGxxakRZeOlg_qDuxmTeQ,Jennilee,38,2012-01-19 23:33:02,74,9,6,,kmwNG5LZSHFmveg6wYYdrw,0,...,1,0,0,0,1,4,0,0,1,0
2105593,tmelBbVBGAzXBVfH2u_R6g,Gerry,19,2009-06-09 16:34:54,14,5,2,,"BFYdCAMFyjYHDwesndEXEg, _9fTIqfSJc7g3V_o76XRVg...",1,...,1,0,0,0,0,1,0,0,0,0
2105594,tpBznnD6uJN3m_pJubj09w,Emily,26,2013-08-13 23:18:11,4,1,2,,"bKV3ly2MuK-K1cptMrFknQ, liel18zRoSB4tEkUP7i6Cg...",0,...,0,0,0,0,1,0,0,0,0,0
2105595,Kst_srPw7GdYydMFYdCtzw,Heatheranne,25,2015-01-10 00:06:25,21,2,5,,"dzHTk52vbGtbktRm_B-wEg, fOfFLV7IbBDN6lzARaLqdg...",0,...,0,0,0,0,0,1,0,0,0,0
2105596,mZl-mH3ZIWLRSd_FfvrXFg,Jessica,30,2015-11-30 21:10:17,27,1,17,,"pou3BbKsIozfH50rxmnMew, JT3rDC7-hprCSObnihMeHw...",3,...,0,1,0,0,0,1,0,0,1,0

In [6]:
#guardamos las primeras 1000 filas en un csv para una mejor comprerension de los datos
df_user.head(1000).to_csv('/Users/luisalbertocerelli/Desktop/00-Todo/Data_Science/01-Full_Time/TPFINAL/Yelp/notebooks_yelp/user_parquet_yelp/user_1000_filas.csv')

In [7]:
df_user.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2105597 entries, 0 to 2105596
Data columns (total 22 columns):
 #   Column              Dtype
---  ------              -----
 0   user_id             object
 1   name                object
 2   review_count        int64
 3   yelping_since       object
 4   useful              int64
 5   funny               int64
 6   cool                int64
 7   elite               object
 8   friends             object
 9   fans                int64
 10  average_stars       float64
 11  compliment_hot      int64
 12  compliment_more     int64
 13  compliment_profile  int64
 14  compliment_cute     int64
 15  compliment_list     int64
 16  compliment_note     int64
 17  compliment_plain    int64
 18  compliment_cool     int64
 19  compliment_funny    int64
 20  compliment_writer   int64
 21  compliment_photos   int64
dtypes: float64(1), int64(16), object(5)
memory usage: 353.4+ MB

In [8]:
#verificar si hay valores nulos
df_user.isnull().sum()

user_id               0
name                  0
review_count          0
yelping_since         0
useful                0
funny                 0
cool                  0
elite                 0
friends               0
fans                  0
average_stars         0
compliment_hot        0
compliment_more       0
compliment_profile    0
compliment_cute       0
compliment_list       0
compliment_note       0
compliment_plain      0
compliment_cool       0
compliment_funny      0
compliment_writer     0
compliment_photos     0
dtype: int64

In [9]:
#verificar si hay valores duplicados
duplicates = df_user.duplicated().sum()
print("Cantidad de valores duplicados: ", duplicates)

Cantidad de valores duplicados:  117700

In [12]:
#acceder a los valores duplicados y hacer un csv con ellos
duplicates = df_user[df_user.duplicated()]
duplicates.to_csv('/Users/luisalbertocerelli/Desktop/00-Todo/Data_Science/01-Full_Time/TPFINAL/Yelp/notebooks_yelp/user_parquet_yelp/valores_duplicados_en_users.csv', index=False)
#hacer un script para que abra el archivo en numbers
os.system('open -a "Numbers" /Users/luisalbertocerelli/Desktop/00-Todo/Data_Science/01-Full_Time/TPFINAL/Yelp/notebooks_yelp/user_parquet_yelp/valores_duplicados_en_users.csv')

0

In [4]:
#una vez analizados los duplicados, procedemos a eliminarlos
df_user = df_user.drop_duplicates()

In [5]:
#verificar si se eliminaron los duplicados
duplicates = df_user.duplicated().sum()
print("Cantidad de valores duplicados: ", duplicates)

Cantidad de valores duplicados:  0

### Estudio de las columnas : 

##### Dado que no hay nulos, se procede a otro tipo de estudio: 

<u>yelping_since (object):</u>  Es la fecha en la que el usuario se unió a Yelp. Es una cadena de texto que generalmente está en formato de fecha (por ejemplo, "2020-01-15"). <span style='color:lightblue'>consideramos que podria ser necesaria a nuestros intereses</span><span style='color:gold'> SE ANALIZARA JUNTO AL EQUIPO</span><span style='color:red'> PERO POR EL MOMENTO SE PROCEDE A BORRAR LA COLUMNA</span>

<u>useful (int64): </u>  Es el número total de veces que las reseñas del usuario han sido marcadas como "útiles" por otros usuarios. Es un número entero.<span style='color:lightpink'>consideramos que no es necesaria a nuestros intereses</span><span style='color:red'> SE PROCEDE A BORRAR LA COLUMNA</span>

<u>funny (int64): </u>  Es el número total de veces que las reseñas del usuario han sido marcadas como "divertidas" por otros usuarios. Es un número entero..<span style='color:lightpink'>consideramos que no es necesaria a nuestros intereses</span><span style='color:red'> SE PROCEDE A BORRAR LA COLUMNA</span>

<u>cool (int64): </u>  Es el número total de veces que las reseñas del usuario han sido marcadas como "geniales" o "interesantes" por otros usuarios. Es un número entero.<span style='color:lightpink'>consideramos que no es necesaria a nuestros intereses</span><span style='color:red'> SE PROCEDE A BORRAR LA COLUMNA</span>

<u>elite (object): </u>  Es una cadena de texto que contiene los años en los que el usuario ha sido considerado "elite" por Yelp, lo que suele indicar un reconocimiento especial. Puede contener múltiples años separados por comas..<span style='color:lightpink'>consideramos que no es necesaria a nuestros intereses</span><span style='color:red'> SE PROCEDE A BORRAR LA COLUMNA</span>

<u> friends (object): </u> Es una cadena de texto que contiene los user_id de los amigos del usuario, generalmente separados por comas. Esto indica las conexiones sociales del usuario dentro de Yelp.<span style='color:lightpink'>consideramos que no es necesaria a nuestros intereses</span><span style='color:red'> SE PROCEDE A BORRAR LA COLUMNA</span>

<u>fans (int64): </u>  Es el número de usuarios que han marcado a este usuario como su "fan". Es un número entero.<span style='color:lightpink'>consideramos que no es necesaria a nuestros intereses</span><span style='color:red'> SE PROCEDE A BORRAR LA COLUMNA</span>

<u>average_stars (float64): </u>  Es la calificación promedio de todas las reseñas que ha escrito el usuario. Es un número decimal que refleja la media de las estrellas que el usuario ha otorgado en sus reseñas.<span style='color:lightpink'>consideramos que no es necesaria a nuestros intereses</span><span style='color:red'> SE PROCEDE A BORRAR LA COLUMNA</span>

<u> compliment_hot (int64):  </u>Es el número de "cumplidos calientes" que el usuario ha recibido. Es un número entero.<span style='color:lightpink'>consideramos que no es necesaria a nuestros intereses</span><span style='color:red'> SE PROCEDE A BORRAR LA COLUMNA</span>

<u> compliment_more (int64): </u> Es el número de "cumplidos más" que el usuario ha recibido. Es un número entero.<span style='color:lightpink'>consideramos que no es necesaria a nuestros intereses</span><span style='color:red'> SE PROCEDE A BORRAR LA COLUMNA</span>

<u>compliment_profile (int64): </u>   Es el número de "cumplidos de perfil" que el usuario ha recibido. Es un número entero.<span style='color:lightpink'>consideramos que no es necesaria a nuestros intereses</span><span style='color:red'> SE PROCEDE A BORRAR LA COLUMNA</span>

<u> compliment_cute (int64):  </u> Es el número de "cumplidos lindos" que el usuario ha recibido. Es un número entero.<span style='color:lightpink'>consideramos que no es necesaria a nuestros intereses</span><span style='color:red'> SE PROCEDE A BORRAR LA COLUMNA</span>

<u> compliment_list (int64): </u> Es el número de "cumplidos de lista" que el usuario ha recibido. Es un número entero.<span style='color:lightpink'>consideramos que no es necesaria a nuestros intereses</span><span style='color:red'> SE PROCEDE A BORRAR LA COLUMNA</span>

<u>compliment_note (int64): </u>   Es el número de "cumplidos de nota" que el usuario ha recibido. Es un número entero.<span style='color:lightpink'>consideramos que no es necesaria a nuestros intereses</span><span style='color:red'> SE PROCEDE A BORRAR LA COLUMNA</span>

<u>compliment_plain (int64):  </u>  Es el número de "cumplidos simples" que el usuario ha recibido. Es un número entero.<span style='color:lightpink'>consideramos que no es necesaria a nuestros intereses</span><span style='color:red'> SE PROCEDE A BORRAR LA COLUMNA</span>

<u>compliment_cool (int64): </u>  Es el número de "cumplidos geniales" que el usuario ha recibido. Es un número entero.<span style='color:lightpink'>consideramos que no es necesaria a nuestros intereses</span><span style='color:red'> SE PROCEDE A BORRAR LA COLUMNA</span>

<u> compliment_funny (int64): </u> Es el número de "cumplidos divertidos" que el usuario ha recibido. Es un número entero.<span style='color:lightpink'>consideramos que no es necesaria a nuestros intereses</span><span style='color:red'> SE PROCEDE A BORRAR LA COLUMNA</span>

<u>compliment_writer (int64): </u>   Es el número de "cumplidos de escritor" que el usuario ha recibido. Es un número entero.<span style='color:lightpink'>consideramos que no es necesaria a nuestros intereses</span><span style='color:red'> SE PROCEDE A BORRAR LA COLUMNA</span>

<u>compliment_photos (int64):</u>  Es el número de "cumplidos de fotos" que el usuario ha recibido. Es un número entero.<span style='color:lightpink'>consideramos que no es necesaria a nuestros intereses</span><span style='color:red'> SE PROCEDE A BORRAR LA COLUMNA</span>

In [5]:
#antes del dropeado, se procede a realizar una copia del dataframe
df_user_copy = df_user.copy()

In [6]:
#se procede a dropear las columnas que no se utilizaran: 'yelping_since','useful','funny','cool', 'elite', 'friends', 'fans', 'average_stars', 'compliment_hot', 'compliment_more', 'compliment_profile', 'compliment_cute', 'compliment_list', 'compliment_note', 'compliment_plain', 'compliment_cool', 'compliment_funny', 'compliment_writer', 'compliment_photos'
df_user_copy = df_user_copy.drop(['yelping_since','useful','funny','cool', 'elite', 'friends','fans', 'average_stars', 'compliment_hot', 'compliment_more', 'compliment_profile', 'compliment_cute', 'compliment_list', 'compliment_note', 'compliment_plain', 'compliment_cool', 'compliment_funny', 'compliment_writer', 'compliment_photos'], axis=1)

In [7]:
#verificar que se hayan eliminado las columnas
df_user_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2105597 entries, 0 to 2105596
Data columns (total 3 columns):
 #   Column        Dtype
---  ------        -----
 0   user_id       object
 1   name          object
 2   review_count  int64
dtypes: int64(1), object(2)
memory usage: 48.2+ MB

In [8]:
#guardamos finalmente el archivo limpio en un archivo parquet
df_user_copy.to_parquet('/Users/luisalbertocerelli/Desktop/00-Todo/Data_Science/01-Full_Time/TPFINAL/Yelp/notebooks_yelp/user_parquet_yelp/user_yelp_listo_para_usar.parquet')

In [9]:
#analizamos el peso del archivo limpio
import os
file_path = '/Users/luisalbertocerelli/Desktop/00-Todo/Data_Science/01-Full_Time/TPFINAL/Yelp/notebooks_yelp/user_parquet_yelp/user_yelp_listo_para_usar.parquet'
print("Tamaño del archivo limpio: ", os.path.getsize(file_path)/1e6, "MB")

Tamaño del archivo limpio:  58.516451 MB