In [1]:
from bs4 import BeautifulSoup
import requests
import csv
import pandas as pd

In [2]:
# URL de la página
url = "https://en.wikipedia.org/wiki/List_of_states_and_territories_of_the_United_States_by_population_density"

# Hacer una solicitud GET a la página
response = requests.get(url)

In [3]:
soup = BeautifulSoup(response.content, "html.parser")

In [4]:
 table = soup.find('table', {'class': 'wikitable'})

In [5]:
#itero sobre table
rows = table.find_all('tr')
data = []
for row in rows:
    cols = row.find_all('td')
    cols = [ele.text.strip() for ele in cols]
    data.append([ele for ele in cols if ele]) 
    #se borran los dos elementos de data
data.pop(0)
data.pop(0)
#se itera sobre data para sacar la primera y la tercera columna
data2 = []
for i in data:
    data2.append([i[0], i[2]])
#se asigna el primer elemento a la lista densidad y el segundo a la lista poblacion
densidad = []
poblacion = []
for i in data2:
    densidad.append(i[0])
    poblacion.append(i[1])

#ahora se recorre la tabla para sacar los nombres de los estados
rows = table.find_all('tr')
data = []
for row in rows:
    cols = row.find_all('th')
    cols = [ele.text.strip() for ele in cols]
    data.append([ele for ele in cols if ele]) 
    #se borran los dos elementos de data
data.pop(0)
data.pop(0)
#Se crea una lista con los nombres de los estados
estados = []
for i in data:
    estados.append(i[0])

In [6]:
#Se crea un diccionario con los datos
datos = {'Estado':estados, 'Densidad':densidad, 'Poblacion':poblacion}

In [7]:
df=pd.DataFrame(datos)

In [8]:
df

                         Estado Densidad    Poblacion
0          District of Columbia   11,131      678,972
1                    New Jersey    1,263    9,290,841
2                  Rhode Island    1,060    1,095,962
3                   Puerto Rico      936    3,205,691
4                 Massachusetts      898    7,001,399
5                       Guam[4]      824      172,952
6                   Connecticut      747    3,617,176
7        U.S. Virgin Islands[4]      737       98,750
8                      Maryland      637    6,180,253
9             American Samoa[4]      578       43,915
10                     Delaware      529    1,031,890
11                      Florida      422   22,610,726
12                     New York      415   19,571,216
13                 Pennsylvania      290   12,961,683
14                         Ohio      288   11,785,935
15  Northern Mariana Islands[4]      274       49,796
16                   California      250   38,965,193
17                     Illinois      226   12,549,689
18                       Hawaii      223    1,435,138
19               North Carolina      223   10,835,491
20                     Virginia      221    8,715,698
21                      Georgia      192   11,029,227
22                      Indiana      192    6,862,199
23               South Carolina      179    5,373,555
24                     Michigan      178   10,037,261
25                    Tennessee      173    7,126,489
26                New Hampshire      157    1,402,054
27                   Washington      118    7,812,880
28                        Texas      117   30,503,301
29                     Kentucky      115    4,526,154
30                    Wisconsin      109    5,910,955
31                    Louisiana      106    4,573,749
32                      Alabama      101    5,108,468
33                     Missouri       90    6,196,156
34                West Virginia       74    1,770,071
35                    Minnesota       72    5,737,915
36                      Vermont       70      647,464
37                      Arizona       65    7,431,344
38                  Mississippi       63    2,939,690
39                     Oklahoma       59    4,053,824
40                     Arkansas       59    3,067,732
41                         Iowa       57    3,207,004
42                     Colorado       57    5,877,610
43                        Maine       45    1,395,722
44                       Oregon       44    4,233,358
45                         Utah       42    3,417,734
46                       Kansas       36    2,940,546
47                       Nevada       29    3,194,176
48                     Nebraska       26    1,978,379
49                        Idaho       24    1,964,726
50                   New Mexico       17    2,114,371
51                 South Dakota       12      919,318
52                 North Dakota       11      783,926
53                      Montana      7.8    1,132,812
54                      Wyoming      6.0      584,057
55                       Alaska      1.3      733,406
56                Contiguous US      113  332,746,351
57                    50 States       95  334,235,923
58             50 States and DC       95  334,914,895
59                United States       96  338,485,999

In [9]:
df=df[~df['Estado'].isin(['District of Columbia','Puerto Rico','American Samoa','U.S. Virgin Islands',
                                  'Northern Mariana Islands','Guam','50 States','50 States and DC','United States','Contiguous US'])]

In [10]:
df.to_csv('Fuentes externas/estados_densidad_poblacion1.csv', index=False, encoding='utf-8')